src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantMapper.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantReader.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantService.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/dto/ParticipantDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipant.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipantRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/presentation/StageParticipantController.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/persistence/TempPoint.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt, src/main/resources/application.yml
stageId, studentId로 포인트를 조회하는 API를 개발하였습니다. `/stage/point/{stage_id}`
status = CONFIRMED인 Stage만 조회가 가능하도록 jpql을 작성하였습니다.
=> [participant] 포인트 조회 server to server API

src/main/kotlin/gogo/gogostage/domain/game/persistence/Game.kt, src/main/kotlin/gogo/gogostage/domain/team/participant/persistence/TeamParticipant.kt
변경된 요구사항으로 인해 Game, TeamParticipant 도메인 객체의 Specs를 수정하였습니다.
- Game 도메인 객체
-  category, ect_name 추가
- 기존 type -> system 컬럼명변경
- TeamParticipant 도메인 객체
- posistionX, positionY 컬럼 추가
=> [stage] Game, TeamParticipant 도메인 세팅 수정

src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/application/TempPointProcessor.kt
매치 정산시 승리팀의 학새들에게도 포인트를 지급하는 정책을 삭제하였습니다.
=> [stage] 매치 정산시 승리팀 학생의 포인트 지급 정책 삭제

src/main/kotlin/gogo/gogostage/domain/community/boardlike/persistence/BoardLike.kt, src/main/kotlin/gogo/gogostage/domain/community/commentlike/persistence/CommentLike.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/Community.kt
- 변경된 요구사항에 맞춰 도메인 세팅을  변경했습니다.
- `tbl_comment_like` 도메인 객체 생성, `tbl_community` 도메인에 stage_id를 매핑하고 경기 category 필드를 추가하였습니다.
=> [community] 커뮤니티 도메인 수정

src/main/kotlin/gogo/gogostage/domain/community/root/persistence/Community.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityRepository.kt, src/main/kotlin/gogo/gogostage/domain/game/persistence/Game.kt, src/main/kotlin/gogo/gogostage/domain/game/persistence/GameRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/maintainer/persistence/StageMaintainer.kt, src/main/kotlin/gogo/gogostage/domain/stage/minigameinfo/persistence/MiniGameInfo.kt, src/main/kotlin/gogo/gogostage/domain/stage/minigameinfo/persistence/MiniGameInfoRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageService.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/dto/StageDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/listener/StageApplicationEventListener.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/event/CreateStageFastEvent.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/Stage.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/StageValidator.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/presentation/StageController.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/persistence/StageRule.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/persistence/StageRuleRepository.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt, src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt, src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt
사설 스테이지 생성 API를 개발하였습니다.
- 스테이지 정보를 요청받아 스테이지를 저장합니다.
- 스테이지 저장 후 `stage_create_fast` 이벤트를 발행합니다. 해당 이벤트를 컨슘하는 MiniGame 서비스는 미니게임을 생성합니다.
=> [stage] 스테이지(사설) 생성 API

src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipant.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipantRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageService.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/dto/StageDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/StageRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/presentation/StageController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
스테이지 참가 API를 개발했습니다.
- 입장코드가 있는 스테이지라면 입장 코드를 확인합니다.
- 스테이지 중복 참가인지 확인합니다.
- 해당 학생의 학교의 스테이지인지 확인합니다.
=> [stage] 스테이지 참가 API

src/main/kotlin/gogo/gogostage/domain/game/application/GameReader.kt, src/main/kotlin/gogo/gogostage/domain/game/persistence/Game.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt, src/main/kotlin/gogo/gogostage/domain/team/participant/persistence/TeamParticipant.kt, src/main/kotlin/gogo/gogostage/domain/team/participant/persistence/TeamParticipantRepository.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamProcessor.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamService.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamValidator.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/dto/TeamApplyDto.kt, src/main/kotlin/gogo/gogostage/domain/team/root/persistence/Team.kt, src/main/kotlin/gogo/gogostage/domain/team/root/persistence/TeamRepository.kt, src/main/kotlin/gogo/gogostage/domain/team/root/presentation/TeamController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
스테이지 경기에 팀 신청 API를 개발하였습니다.
- 스테이지 참여자인지, 해당 스테이지가 모집중인지, 경기의 인원이 맞는지, 팀의 인원이 이미 참여했는지와 같은 검증 처리를 진행 후 팀을 저장합니다.
=> [stage] 스테이지 경기 팀 신청 API

src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchMapper.kt, src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchReader.kt, src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchService.kt, src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/match/root/application/dto/MatchDto.kt, src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchCustomRepository.kt, src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchCustomRepositoryImpl.kt, src/main/kotlin/gogo/gogostage/domain/match/root/presentation/MatchController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
매치 상세 조회 API를 개발하였습니다.
- 해당 유저가 스테이지에 참여하고 있는지 검증합니다.
- PathVariable로 받은 matchId로 매치를 조회하여 반환합니다.
=> [match] 매치 상세 조회 API

src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageMapper.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageReader.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageService.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/dto/StageDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/Stage.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/StageRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/presentation/StageController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
스테이지 조회 API를 개발하였습니다.
- 해당 사용자의 학교에 포함된 스테이지를 조회하여 반환합니다.
=> [stage] 스테이지 조회 API

src/main/kotlin/gogo/gogostage/domain/game/application/GameMapper.kt, src/main/kotlin/gogo/gogostage/domain/game/application/GameReader.kt, src/main/kotlin/gogo/gogostage/domain/game/application/GameService.kt, src/main/kotlin/gogo/gogostage/domain/game/application/GameServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/game/application/dto/GameDto.kt, src/main/kotlin/gogo/gogostage/domain/game/persistence/GameRepository.kt, src/main/kotlin/gogo/gogostage/domain/game/presentation/GameController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
스테이지에 등록된 경기 조회 API를 개발하였습니다.
- 해당 유저가 스테이지에 참여하고 있는지 검증합니다.
- PathVariable로 받은 stageId로 스테이지에 등록된 경기를 조회합니다.
=> [game] 스테이지에 등록된 경기 조회 API

src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageMapper.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageReader.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageService.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/dto/StageDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/StageRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/presentation/StageController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
내가 참여한 스테이지 조회 API를 개발하였습니다.
- 해당 유저가 참여한 스테이지를 조회하여 반환합니다.
=> [stage] 내가 참여한 스테이지 조회 API

src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchMapper.kt, src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchReader.kt, src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchService.kt, src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchRepository.kt, src/main/kotlin/gogo/gogostage/domain/match/root/presentation/MatchController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
내가 배팅한 매치 조회 API를 개발하였습니다.
- 해당 유저가 스테이지에 참여하고 있는지 검증합니다.
- 해당 유저의 배팅 정보를 Betting 서비스의 일괄 조회 API로 받아와 매치를 조회하여 반환합니다.
=> [match] 내가 배팅한 매치 조회 API

src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantReader.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantService.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/dto/ParticipantDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/presentation/StageParticipantController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
학생 ID, 스테이지 ID로 해당 학생이 스테이지 참여자인지 확인하는 server to server API를 개발하였습니다.
=> [stage] 학생 ID, 스테이지 ID로 해당 학생이 스테이지 참여자인지 확인 API

src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamMapper.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamReader.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamService.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamValidator.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/dto/TeamApplyDto.kt, src/main/kotlin/gogo/gogostage/domain/team/root/persistence/TeamRepository.kt, src/main/kotlin/gogo/gogostage/domain/team/root/presentation/TeamController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
경기에 출전하는 팀을 조회하는 api를 개발하였습니다
* gameId를 Path로 받아 game을 조회를 하고 토큰을 통해 student를 가져옵니다.
* studentId와 game.stage.id로 해당 스테이지에 존재하는 사람인지 검증을 합니다.
* 그 후 team 엔티티들을 찾아 mapper를 거쳐 반환되게 됩니다.
=> [team] 경기에 출전하는 팀 조회하기 API

src/main/kotlin/gogo/gogostage/global/internal/student/stub/StudentStub.kt
학생 정보 인터널 API 스펙을 수정하였습니다.
deviceToken 필드 non-null -> nullable
=> [internal] 학생 정보 인터널 API 스펙 수정

src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/presentation/StageController.kt
validJoin 메서드가 잘못 조건문이 되어있어 수정 및 StageController 메서드와 서비스 Name 불일치문제를 수정하였습니다.
* CreateFast로 되어있던 컨트롤러 method 이름을 서비스와 맞게 올바르게 수정하였습니다
* validJoin에서 학교 검증 로직이 잘못되어있어 수정하였습니다.
=> [stage] 잘못된 valid 수정

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt, src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityReader.kt, src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityRepository.kt
커뮤니티 게시글을 생성할 때 GameCategory가 올바르게 들어가지 않는 문제를 해결하였습니다.
* 커뮤니티를 조회할때 StageId로만 조회하였을 때 여러 커뮤니티가 조회되어 board에 community가 잘못들어가여 커뮤니티 조회를 StageIdAndCategory로 변경하여 올바르게 조회되도록 수정하였습니다
=> [stage] 커뮤니티 게시글 생성 문제

src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
사설 스테이지 생성 이벤트 객체 생성시 minPoint 필드에 maxPoint 를 주입하는 문제를 해결하였습니다.
- 공식 스테이지 생성 API url의 security 매핑을 STAFF authority로 수정하였습니다.
=> [stage] 스테이지 생성 이벤트 수정

src/main/kotlin/gogo/gogostage/global/config/PropertiesScanConfig.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
Internal API의 security IP 필터링을 추가하였습니다.
=> [global] internal API의 security IP 필터링 추가

src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt
스테이지 생성시 관리자 추가 안할시 생성 요청한 학생을 추가하도록 수정하였습니다.
- 스테이지 생성시 관리자 추가를 안하는 경우 요청한 학생을 관리자로 추가하도록 수정하였습니다.
=> [stage] 스테이지 생성시 관리자 추가 안할시 본인 추가

src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantMapper.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantService.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/dto/ParticipantDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/presentation/StageParticipantController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
브랜치의 실수로 잘못 머지 되어 내 포인트를 조회하기 API를 다시 개발하였습니다.
* 토큰과 stageId로 해당 스테이지와 student를 호출하여 해당 학생이 참여하고 있는지 확인합니다.
* stageParticipant 객체에 해당 student가 가지고 있는 point를 map을 거쳐 반환합니다.
=> [stage] 내 포인트 조회하기

src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipateProcessor.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/event/TicketPointMinusEvent.kt
ticket_shop_buy를 컨슘한 뒤 ticket_point_minus 이벤트 스펙이 Update가 되어 있지 않아 shopReceiptId를 추가하였습니다.
* TicketPointMinusEvent에 shopReceiptId 추가하였습니다.
=> [stage] 상점 티켓 구매 이벤트 스펙 변경

src/main/kotlin/gogo/gogostage/domain/game/application/GameMapper.kt, src/main/kotlin/gogo/gogostage/domain/game/application/dto/GameDto.kt
teamMinCapacity, teamMaxCapacity를 반환하는 API가 존재하지 않아 추가하였습니다.
QueryGameInfoDto에 teamMinCapacity, teamMaxCapacity 추가반환하도록 추가하였습니다.
=> [stage] 스테이지 경기 조회 response 변경

src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamMapper.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamReader.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamService.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/dto/TeamApplyDto.kt, src/main/kotlin/gogo/gogostage/domain/team/root/presentation/TeamController.kt
팀 상세보기 API가 누락되어 다시 추가하였습니다
* 토큰으로 student를 가져오고 teamId로 team을 가져옵니다.
* 해당 student가 stage에 존재하는지 검증합니다.
=> [team] 팀 상세보기 API

README.md, src/main/kotlin/gogo/gogostage/global/error/ErrorResponse.kt, src/main/kotlin/gogo/gogostage/global/error/GlobalExceptionHandler.kt
예외 핸들러에서 핸들링하는 예외를 추가하였습니다.
- validation, constraintViolation, feign, runtimeException의 예외들을 명시적으로 핸들링하도록 수정하였습니다.
=> [global] 예외 핸들러 수정

src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantReader.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipantServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/persistence/TempPointRepository.kt
내 임시포인트 조회시 반영되지 않은 임시포인트만 조회하도록 수정하였습니다.
- 내 임시포인트 조회시 반영되지 않은 임시포인트만 조회하도록 JPA 쿼리 메서드를 수정하였습니다.
=> [temp-point] 내 임시포인트 조회시 반영되지 않은 임시포인트만 조회

src/main/kotlin/gogo/gogostage/domain/community/board/persistence/Board.kt, src/main/kotlin/gogo/gogostage/domain/community/comment/persistence/Comment.kt, src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt
게시글, 댓글 title, content 길이를 수정하였습니다.
- 게시글 title 30자, content 1000자
- 댓글 content 300자
=> [community] 게시글, 댓글 title, content 길이 수정

.github/workflows/gogo-stage-prod-cd.yml, .github/workflows/gogo-stage-prod-ci.yml, DockerFileProd
=> [global] 상용 환경 ci/cd 스크립트

src/main/resources/application.yml
- applicaiton yml에 prod profile을 추가하였습니다.
=> v2025.4.1.3

DockerFileStage
prod docker file jar file naming 수정
=> v2025.4.1.4

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
커뮤니티 게시글 좋아요, 불러오기 문제를 해결하였습니다.
* 커뮤니티 게시글 좋아요를 검증하는 과정에서 studentId가 잘못들어가 있는 문제를 수정하였습니다.
* 커뮤니티 게시글 불러오기에서 욕설 필터 where문이 들어가는 조건이 잘못되어 수정하였습니다
=> [community] 커뮤니티 게시글 좋아요, 불러오기 문제

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
Reverts team-gogo/gogo-stage#124
=> Revert "[community] 커뮤니티 게시글 좋아요, 불러오기 문제"

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
=> v2025.4.1.5

src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamValidator.kt, src/main/kotlin/gogo/gogostage/domain/team/root/persistence/TeamRepository.kt
요구사항 변경으로 인해 중복된 팀 이름으로 팀을 신청할 수 없도록 체크하였습니다.
=> [team] 팀 신청시 팀 이름 중복 체크

src/main/kotlin/gogo/gogostage/domain/stage/rule/application/StageRuleMapper.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/application/StageRuleReader.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/application/StageRuleService.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/application/StageRuleServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/application/dto/StageRuleDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/persistence/StageRule.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/persistence/StageRuleRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/rule/presentation/StageRuleController.kt, src/main/kotlin/gogo/gogostage/global/cache/CacheConstant.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
스테이지 규칙 조회 API를 개발하였습니다.
- stage ID를 요청받아 해당 스테이지의 규칙을 조회합니다.
- 요청한 학생과 조회하려는 스테이지에 참여하고 있는지 검증합니다.
- 해당 Response에 캐시를 적용하였습니다. 스테이지 규칙은 변경되지 않아 이빅트 트리거를 지정해두지 않았습니다.
=> [rule] 스테이지 규칙 조회 API

src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchRepository.kt
match repository 메서드의 파라미터 네이밍의 잘못된 부분을 수정하였습니다.
=> [match] repository 메서드 파라미터 네이밍 수정

src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchRepository.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
=> v2024.4.3.2

src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamValidator.kt
팀 신청시 팀 이름이 최대 6글자를 넘을 수 없도록 검증식을 추가하였습니다.
=> [team] 팀 이름 최대 글자 검증 추가

src/main/kotlin/gogo/gogostage/domain/game/application/GameMapper.kt, src/main/kotlin/gogo/gogostage/domain/game/application/dto/GameDto.kt
대진표 조회 API 스펙을 수정하였습니다.
nullable한 필드인 match의 team id와 team name의 예외 처리를 하였습니다.
=> [game] 대진표 조회 API 스펙 수정

src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchReader.kt, src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchRepository.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageService.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/dto/StageDto.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/presentation/StageController.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt, src/main/kotlin/gogo/gogostage/global/feign/client/BettingClient.kt, src/main/kotlin/gogo/gogostage/global/internal/betting/api/BettingApi.kt, src/main/kotlin/gogo/gogostage/global/internal/betting/api/BettingApiImpl.kt, src/main/kotlin/gogo/gogostage/global/internal/betting/stub/BettingStub.kt
내가 파산했는지 확인하는 API를 개발하였습니다.
아래와 같은 조건을 검사하여 파산 여부를 반환합니다.
- 현재 포인트가 0보다 크다면 파산하지 않았다.
- 아직 반영되지 않은 임시 포인트의 합이 0보다 크다면 파산하지 않았다.
- 아직 정산되지 않은 모든 배팅의 배팅 포인트의 합이 0보다 크다면 파산하지 않았다.
- 위 조건에 모두 부합하지 않는다면 해당 학생은 파산했다.
=> [stage] 내가 파산했는지 확인하기 API

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityValidator.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
rank에서 페이징 처리를 할 때 page와 size가 음수일 경우 예외처리를 하였습니다.
rank api에 validPageAndSize 추가
=> [stage] rank 페이징 예외 처리

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityMapper.kt, src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt, src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityService.kt, src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt, src/main/kotlin/gogo/gogostage/domain/community/root/presentation/CommunityController.kt
커뮤니티를 client 익명화로 전환하였습니다.
- 필터 관련 조건식을 수정하였습니다.
- 커뮤니티 관련 조회 API 스펙을 수정하였습니다.
- 필터 여부에 대해 게시글 상세보기 캐시를 적용시켰으며, 이빅트시 필터 true, false 캐시 모두 이빅트 하도록 하였습니다.
=> [community] 커뮤니티 익명화

src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt, src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
=> [community] 욕설 필터 조건식, 검증식 수정

build.gradle.kts, src/main/kotlin/gogo/gogostage/domain/community/board/application/BoardProcessor.kt, src/main/kotlin/gogo/gogostage/domain/community/board/persistence/Board.kt, src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt, src/main/kotlin/gogo/gogostage/domain/image/application/ImageMapper.kt, src/main/kotlin/gogo/gogostage/domain/image/application/ImageService.kt, src/main/kotlin/gogo/gogostage/domain/image/application/ImageServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/image/application/ImageValidator.kt, src/main/kotlin/gogo/gogostage/domain/image/application/dto/ImageDto.kt, src/main/kotlin/gogo/gogostage/domain/image/presentation/ImageController.kt, src/main/kotlin/gogo/gogostage/global/aws/s3/S3Config.kt, src/main/kotlin/gogo/gogostage/global/aws/s3/S3Uploader.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
이미지를 업로드 할 수 있는 api를 개발하였습니다.
* image를 formData로 body를 통해 보내면 s3를 통해 저장 후 해당 url을 반환하도록 하였습니다.
=> [image] 이미지 업로드 API

src/main/kotlin/gogo/gogostage/domain/coupon/result/persistence/CouponResult.kt, src/main/kotlin/gogo/gogostage/domain/coupon/result/persistence/CouponResultRepository.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/application/CouponMapper.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/application/CouponProcessor.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/application/CouponReader.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/application/CouponService.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/application/CouponServiceImpl.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/application/CouponValidator.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/application/dto/CouponDto.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/persistence/Coupon.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/persistence/CouponRepository.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/presentation/CouponController.kt, src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipant.kt, src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
쿠폰 기능을 개발했습니다.
- Coupon, CouponResult 엔티티를 생성했습니다.
- 일반, 랜덤 타입 쿠폰 기능을 개발했습니다.
- 쿠폰 조회, 쿠폰 사용 API를 개발했습니다.
=> [coupone] 쿠폰 API

src/main/kotlin/gogo/gogostage/domain/coupon/result/persistence/CouponResult.kt, src/main/kotlin/gogo/gogostage/domain/coupon/root/persistence/Coupon.kt
연관관계 필드에 Column 어노테이션을 JoinColumn 어노테이션으로 수정했습니다.
=> [coupon] 연관관계 필드 JoinColumn 어노테이션

src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt, src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt
페이징된 게시글을 가져올 때 DTO에 viewCount를 추가하여 반환하도록 변경하였습니다.
* BoardDto에 viewCount 추가
=> [community] 게시글 페이징 반환값 변경
