team-gogo/gogo-stage

build.gradle.kts
src/main/kotlin/gogo/gogostage/domain/game/persistence/Game.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/Match.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchRepository.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipateProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipant.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipantRepository.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/StageRepository.kt
src/main/kotlin/gogo/gogostage/domain/team/root/persistence/Team.kt
src/main/kotlin/gogo/gogostage/global/error/GlobalExceptionHandler.kt
src/main/kotlin/gogo/gogostage/global/kafka/KafkaEventPublisher.kt
src/main/kotlin/gogo/gogostage/global/kafka/configuration/KafkaConsumerConfig.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/MatchBettingConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/StagePublisher.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/MatchBettingEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/MatchBettingFailedEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt
src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt
src/main/kotlin/gogo/gogostage/global/publisher/TransactionEventPublisher.kt
src/main/resources/application.yml

배팅 완료시 발행하는 이벤트를 Stage 서비스가 핸들링하는 작업을 작성하였습니다.
1. 배팅 서비스에서 배팅 완료시 `match_betting` 토픽에 발행한 이벤트를 Stage 서비스에서 컨슘합니다.
2. 해당 배팅이 유효한지 검증합니다. (a. 배팅 가능 시간인가?, b. 해당 매치에 배팅한 학생이 출전하는가?)
3. 이벤트 본문에 따라 해당 학생의 포인트를 차감합니다.
2.1 Match에 총 배팅된 포인트를 올리는 작업이 포함되어 있어 추후에 캐싱 적용시 캐시 업데이트가 필요합니다.
4. 해당 Match에 배팅한 Team에 배팅한 포인트를 추가하여 업데이트합니다.
- 만약 차감 작업이 실패시 위 작업의 트랜잭션은 롤백 되고 `match_betting_failed` 이벤트를 발행하여 배팅 서비스의 보상 트랜잭션 작업을 요구합니다.

[stage] 배팅 이벤트 핸들링

---

src/main/kotlin/gogo/gogostage/GogoStageApplication.kt
src/main/kotlin/gogo/gogostage/domain/match/result/persistence/MatchResult.kt
src/main/kotlin/gogo/gogostage/domain/match/result/persistence/MatchResultRepository.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/Match.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipant.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/application/TempPointProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/persistence/TempPoint.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/persistence/TempPointRepository.kt
src/main/kotlin/gogo/gogostage/domain/team/root/persistence/TeamRepository.kt
src/main/kotlin/gogo/gogostage/global/kafka/configuration/KafkaConsumerConfig.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/MatchBatchConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/MatchBettingConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/BatchAdditionTempPointFailedEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/MatchBatchEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt
src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt
src/main/kotlin/gogo/gogostage/global/schedule/TempPointScheduler.kt

배팅 서비스에서 정산 후 이벤트를 컨슘하여 예측에 성공한 학생들의 **임시포인트를 지급, 매치 결과 저장, 매치 종료 처리**하는 기능을 개발하였습니다.
- `match_batch` 토픽의 이벤트를 컨슘하여 예측 성공한 학생에게 임시포인트 지급, 매치 결과 저장, 매치 종료 처리를 진행합니다.
- 임시포인트는 5분 5초 후의 시간으로 만료 시간을 설정하여 저장합니다. (`TempPointScheduler` 스케쥴러가 30초마다 만료시간을 확인하여 포인트로 합산합니다.)
- 해당 매치의 승리팀 학생들에게 해당 매치에 배팅된 포인트 10%씩 임시포인트로 지급합니다.
- 해당 작업을 진행하다 예외가 발생시 `batch_addition_temp_point_failed` 이벤트를 발행합니다. 해당 이벤트를 컨슘한 Betting 서비스에서 해당 정산에 대한 보상 트랜잭션을 실행시키길 기대합니다.

[stage] 배팅 정산 이벤트 핸들링

---

src/main/kotlin/gogo/gogostage/domain/match/result/persistence/MatchResultRepository.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchReader.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/Match.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/application/TempPointProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/persistence/TempPointRepository.kt
src/main/kotlin/gogo/gogostage/global/kafka/configuration/KafkaConsumerConfig.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/BatchCancelConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/BatchCancelDeleteTempPointFailedEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/BatchCancelEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt
src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt

Betting 서비스에서 발급하는 정산 취소 이벤트를 핸들링합니다.
- batch_cancel 이벤트를 핸들링하여 해당 배치에 대한 임시 포인트를 삭제합니다.
- 만약 임시포인트가 이미 반영되었다면 batch_cancel_delete_temp_point_failed 이벤트를 발행하며 Betting 서비스에서 취소된 정산을 복구하기를 기대합니다.

[stage] 정산 취소 이벤트 핸들링

---

src/main/kotlin/gogo/gogostage/domain/community/root/persistence/Community.kt
src/main/kotlin/gogo/gogostage/domain/stage/minigameinfo/persistence/MiniGameInfo.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageMapper.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageService.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/dto/StageDto.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/listener/StageApplicationEventListener.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/event/CreateStageOfficialEvent.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/Stage.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/presentation/StageController.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt
src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt

공식 스테이지 생성 API를 개발하였습니다.
- STAFF(인증된 학교 관계자) 권한의 사용자만 요청을 보낼 수 있습니다.
- 스테이지 생성 요청시 스테이지를 저장 후 `stage_create_official` 토픽에 miniGame, shop 관련 정보가 담긴 이벤트를 발행합니다.
- `stage_create_official` 토픽에서 이벤트를 컨슘한 MiniGame, Shop 서비스는 해당 정보를 바탕으로 각각 미니게임, 상점을 생성합니다.

[stage] 스테이지(공식) 생성 API

---

src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipateProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/listener/StageParticipantApplicationEventListener.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/event/TicketPointMinusEvent.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/listener/StageApplicationEventListener.kt
src/main/kotlin/gogo/gogostage/global/kafka/configuration/KafkaConsumerConfig.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/TicketAdditionFailedConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/TicketShopBuyConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/TicketAdditionFailedEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/TicketPointMinusFailedEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/TicketShopBuyEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt
src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt
src/main/kotlin/gogo/gogostage/global/saga/TicketAdditionFailedSaga.kt

Shop 서비스에서 티켓 구매시 이벤트 핸들링을 처리했습니다.
- `ticket_shop_buy`: 해당 이벤트를 컨슘하여 구매 금액 만큼의 포인트를 차감합니다.
- V -> `ticket_point_minus`: 해당 이벤트를 발행합니다. MiniGame 서비스에서 컨슘하여 타켓 수량을 추가합니다.
- X -> `ticket_point_minus_failed`: 포인트 차감 중 예외 발생시 해당 이벤트를 발행하여 Shop 서비스에서 롤백 처리를 기대합니다.
- `ticket_addition_failed`: 해당 이벤트를 컨슘하여 포인트를 롤백합니다. (MiniGame 서비스에서 티켓 수량 추가 실패시 발행됨)

[stage] Shop 서비스 티켓 구매 이벤트 핸들링

---

build.gradle.kts
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityReader.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityService.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityValidator.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/Community.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/presentation/CommunityController.kt
src/main/kotlin/gogo/gogostage/global/config/QueryDslConfig.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
src/main/kotlin/gogo/gogostage/global/feign/client/StudentClient.kt
src/main/kotlin/gogo/gogostage/global/internal/student/api/StudentApi.kt
src/main/kotlin/gogo/gogostage/global/internal/student/api/StudentApiImpl.kt
src/main/kotlin/gogo/gogostage/global/internal/student/stub/StudentStub.kt

경기 게시판 조회 API를 개발하였습니다.
* page, size, gameType, sortType을 QueryString을 받고 stageId를 Path를 입력하여 요청을 받는다.
* stageId를 가지고 Community를 조회 후 QuertString으로 받은 값을 바탕으로 queryDsl을 사용하여 반환한다.

[community] 경기 게시판 검색 API

---

src/main/kotlin/gogo/gogostage/domain/community/boardlike/persistence/BoardLikeRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/comment/persistence/Comment.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityReader.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityService.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/presentation/CommunityController.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt

경기 게시글 상세보기 API를 개발하였습니다.
* boardId를 Path를 받아 해당 board를 조회 후 board의 Author과 board에 대한 comment를 조회합니다.
* comment의 Author을 불러 Dto에 넣습니다.
* 또한, board와 comment의 좋아요 여부를 같이 반환합니다.

[community] 경기 게시글 상세보기 API

---

src/main/kotlin/gogo/gogostage/domain/community/board/application/BoardReader.kt
src/main/kotlin/gogo/gogostage/domain/community/board/persistence/Board.kt
src/main/kotlin/gogo/gogostage/domain/community/boardlike/persistence/BoardLike.kt
src/main/kotlin/gogo/gogostage/domain/community/boardlike/persistence/BoardLikeRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityReader.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityService.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt
src/main/kotlin/gogo/gogostage/domain/community/root/presentation/CommunityController.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt

경기 게시글을 좋아요할 수 있는 API를 추가하였습니다
* boardId를 받아 해당 board를 조회합니다.
* board와 토큰을 통해 student를 가져와 proceessor로 이동합니다.
* processor에서 boardId와 studentId로 boardLike 여부를 boolean으로 반환합니다.
* 만약에 존재한다면 해당 boardLike를 지우고 false를 반환합니다.
* 존재하지 않는다면 boardLike 엔티티를 생성하여 추가합니다.

[community] 경기 게시글 좋아요 API

---

src/main/kotlin/gogo/gogostage/domain/community/comment/persistence/Comment.kt
src/main/kotlin/gogo/gogostage/domain/community/comment/persistence/CommentRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityMapper.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityService.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt
src/main/kotlin/gogo/gogostage/domain/community/root/presentation/CommunityController.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt

경기 게시글 댓글을 작성하는 API를 추가하였습니다.
* boardId, WriteBoardCommentReqDto을 Path와 Body로 요청을 받습니다.
* 받은 후, 같이 보낸 토큰을 가지고 student를 가져옵니다.
* 그 후 boardId로 board를 조회합니다.
* board와 student, WriteBoardCommentReqDto를 가지고 comment를 저장합니다.

[comment] 경기 게시글 댓글 작성 API

---

src/main/kotlin/gogo/gogostage/domain/game/persistence/Game.kt
src/main/kotlin/gogo/gogostage/domain/game/persistence/GameRepository.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/Match.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipateProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageService.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/dto/StageDto.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/listener/StageApplicationEventListener.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/event/StageConfirmEvent.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/Stage.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/presentation/StageController.kt
src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamValidator.kt
src/main/kotlin/gogo/gogostage/domain/team/root/persistence/Team.kt
src/main/kotlin/gogo/gogostage/domain/team/root/presentation/TeamController.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt
src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt

스테이지 확정 API를 개발하였습니다.
- 사설, 공식 스테이지를 확정합니다.
- 단판, 토너먼트, 풀리그 경기 시스템을 기준으로 나누어 매치를 생성, 저장합니다.
- 스테이지 관려지인지, 모집 중인 스테이지인지, 모든 경기를 확정했는지, 각 시스템 경기마다 매치 수가 올바른지 validation 합니다.
- 확정된 팀은 isParticipant를 true로 변경, stage는 CONFIRM 상태로 변경합니다. 이후에 `stage_confrim` 토픽에 이벤트를 발행하여 MiniGame, Shop 서비스의 상태를 변경합니다.

[stage] 스테이지 확정 API

---

src/main/kotlin/gogo/gogostage/domain/game/persistence/Game.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchProcessor.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/Match.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchRepository.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/persistence/StageParticipant.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/application/TempPointProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt
src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamValidator.kt
src/main/kotlin/gogo/gogostage/domain/team/root/persistence/Team.kt
src/main/kotlin/gogo/gogostage/domain/team/root/persistence/TeamRepository.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/BatchCancelConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/MatchBatchConsumer.kt

매치 정산, 정산취소 이벤트 핸들링 후처리 작업을 하였습니다.
정산 이벤트
- 매치 정산시 해당 경기의 모든 매치가 종료되었다면 해당 경기를 종료 처리합니다.
- 토너먼트 매치가 정산되었다면 결승전이 아니라면 승리 팀을 다음 매치에 진출 시킵니다.
- 승리팀 win count를 증가시킵니다.
정산 취소 이벤트
- 마지막 매치가 정산 취소시 경기 종료 롤백처리
- 결승전 매치가 아닌 토너먼트일 경우 상위 매치로 올라간 팀 정보 삭제 처리

[stage] 매치 정산, 정산취소 이벤트 핸들링 후처리 작업

---

src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageMapper.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/dto/StageDto.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/event/CreateStageFastEvent.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/event/CreateStageOfficialEvent.kt

스테이지 생성 관련 로직을 수정하였습니다.
- 스테이지 생성시 누락되어있던 `initialTicketCount` - 미니게임 초기 보유 티켓 개수 필드를 추가하였습니다. (reqeust, event)
- Maintainer 생성시 중복을 없애고 본인이 관리자로 중복 등록되는 경우를 체크했습니다.
- 미니게임이 활성화 되지 않았는데 상점을 활성화 하는 경우를 체크했습니다.

[stage] 스테이지 생성 로직 수정

---

src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchMapper.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchReader.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchService.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/dto/MatchDto.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/Match.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchCustomRepository.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchCustomRepositoryImpl.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchRepository.kt
src/main/kotlin/gogo/gogostage/domain/match/root/presentation/MatchController.kt
src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt
src/main/kotlin/gogo/gogostage/global/feign/client/BettingClient.kt
src/main/kotlin/gogo/gogostage/global/internal/betting/api/BettingApi.kt
src/main/kotlin/gogo/gogostage/global/internal/betting/api/BettingApiImpl.kt
src/main/kotlin/gogo/gogostage/global/internal/betting/stub/BettingStub.kt

매치 검색하기 API를 개발하였습니다.
- StageValidator로 요청을 보낸 사용자가 해당 스테이지에 참여하고 있는지 검증합니다.
- stageId, y, m, d를 받아 매치를 검색하고 해당 유저의 배팅 정보를 Betting 서비스에서 rest 통신을 통해 일괄적으로 받아옵니다.

[stage] 매치 검색하기 API

---

src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipateProcessor.kt
src/main/kotlin/gogo/gogostage/global/kafka/configuration/KafkaConsumerConfig.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/MiniGameBetCompletedConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/MiniGameBetCompletedEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/MiniGameBetCompletedFailedEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt
src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt

MiniGame 서비스 미니게임 완료 이벤트 핸들링 작업을 구현하였습니다.
- `minigame_bet_completed` 토픽에서 이벤트를 컨슘하여 유저의 포인트를 추가하거나 깎습니다.
- 해당 작업 중 예외가 발생시 `minigame_bet_completed_failed` 토픽에 이벤트를 발행하여 해당 미니게임 롤백을 기대합니다.

[stage] MiniGame 서비스 미니게임 완료 이벤트 핸들링

---

src/main/kotlin/gogo/gogostage/domain/stage/root/application/StageValidator.kt
src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamService.kt
src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/team/root/presentation/TeamController.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt

경기에 신청된 팀을 조회하는 API를 개발하였습니다.
* gameId를 받아 game을 검색하고 student를 토큰을 통해 찾습니다.
* 해당 student가 stageParticipant인지 검증 후 gameId와 isParticipating을 false로 하여 검색한 후 mapper를 거쳐 반환되게 됩니다.

[team] 경기에 신청된 팀 조회하기 API

---

build.gradle.kts
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchMapper.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/dto/MatchDto.kt

매치결과 조회시 tempPointExpiredDate 필드를 추가하였습니다.
- `tempPointExpiredDate` 해당 필드는 해당 매치의 임시포인트가 반영되는 시간입니다. (종료 기준으로 +5분 후)

[match] 매치결과 조회시 tempPointExpiredDate 필드 추가

---

src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt

커뮤니티 게시글 상세조회가 status Code만 반횐이 되고 바디가 오지 않는 문제가 생겨 해결하였습니다
문제 상황 파악 중 AuthorDto를 만드는 과정에서 NPE가 발생하는 상황이 발생하여 StudentIds를 추출하는 방식을 변경하여 해결하였습니다.
정확히 파악은 되지 않았지만 테스트 결과 성공하였습니다.

[stage] 커뮤니티 게시글 상세조회 반환되지 않는 문제

---

src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt

커뮤니티 게시글을 조회할 때 totalPage가 정확하게 나오지 않는 문제를 해결하였습니다.
직접 totalPage를 구하는 로직의 문제가 생겨 findAll(pageable).totalPages 를 사용하여 totalPage를 구하는 로직으로 변경하였습니다

[stage] 커뮤니티 게시글 조회 문제

---

src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchMapper.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/dto/MatchDto.kt

매치 검색 API 스펙을 요구사항에 맞게 수정하였습니다.
- `isPlayer`: 요청을 보낸 학생이 해당 매치(a team, b team)에 출전하는지
- `isNotice`: 해당 매치에 알림 설정을 했는지

[match] 매치 검색 DTO 필드 추가

---

src/main/kotlin/gogo/gogostage/domain/community/board/persistence/Board.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityReader.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt

게시글 상세보기에서 게시글/댓글의 isLike의 값이 일치하지않는 문제가 발생하여서 fix하였습니다.
* commentLikeCommentIds의 where문에서 studentId를 비교하는 과정에서 해당 페이지 요청을 보낸 유저가 아닌 글쓴이와 정보를 비교하여 잘못된 정보를 가져오는 문제가 있어 수정하였습니다
* 또한, commentLikeCommentIds의 값이 CommentId가 아닌 CommentLikeId를 잘못 불러와 비교하는 과정에서 좋아요를 눌렀는지 인식이 되지 않는 문제가 생겨 수정하였습니다
* comments를 가져오는 과정의 where 조건문에 문제가 있어 수정하였습니다.
* writeComment를 하면 board에서 commentCount가 올라가지 않는 문제가 있어 fixed하였습니다.
* stageBoard 조회 api에서 commentCount 필드를 추가 반환하게 변경하였습니다.

[stage] 커뮤니티 게시글/댓글 좋아요 반환 문제

---

src/main/kotlin/gogo/gogostage/domain/match/result/persistence/MatchResult.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchMapper.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/persistence/TempPointRepository.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/MatchBatchEvent.kt

매치 도메인에 임시포인트 만료일 필드를 추가하였습니다.
- 매치 검색시 임시포인트 만료일을 매치 종료시간 기준 +5분으로 내려주고 있는 문제가 있었습니다.
- 매치 정산시 매치 도메인의 임시포인트 만료일에 현재시간 +5분을 저장하고 매치 검색시 해당 필드를 내려줍니다.

[match] 매치 임시포인트 만료일 필드 추가

---

src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/temppoint/application/TempPointProcessor.kt

매치 정산 취소 이벤트(`match_batch_cancel`) 핸들링시 임시포인트 반영 여부 검증식을 수정했습니다.
- 만약 정산 후 임시포인트를 받은 학생이 아무도 없는 경우 정산 취소시 임시포인트가 존재하지 않아서 이미 반영된 것으로 판단하는 이슈를 확인했습니다.
- #97 해당 작업에서 추가했던 임시포인트 반영 시간을 기준으로 검증하도록 수정하였습니다.

[match] 매치 정산 취소 이벤트 핸들링시 임시포인트 반영 여부 검증식 수정

---

src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamMapper.kt
src/main/kotlin/gogo/gogostage/domain/team/root/application/dto/TeamApplyDto.kt

api specs에 winCount가 존재하지만 api에 누락되어 추가하였습니다
* GameTeamDto에 winCount를 추가하여 mapper에서 it.winCount로 초기화 하도록 변경하였습니다

[team] 경기에 출전하는 팀 조회 response 추가 반환

---

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityReader.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt

커뮤니티 욕설 필터에 따른 글 조회 적용과 해당 학생이 해당 스테이지에 참여중인지 검증하는 로직을 추가하였습니다
* community관련 API에 validStage를 추가하여 해당 유저가 스테이지에 참여중인지 검증하는 로직을 추가하였습니다.
* 커뮤니티 욕설 필터관련 조회 로직에 만약에 필터를 켰다면 욕설필터에 걸리지 않은 글만 반환합니다. 반면에 필터가 꺼져있다면 모든 글을 반환하게 됩니다.

[stage] 커뮤니티 욕설 필터에 따른 글 조회 적용

---

src/main/kotlin/gogo/gogostage/domain/community/board/application/BoardReader.kt
src/main/kotlin/gogo/gogostage/domain/community/board/persistence/BoardRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/comment/application/CommentReader.kt
src/main/kotlin/gogo/gogostage/domain/community/comment/persistence/CommentRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityReader.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt

커뮤니티 게시글, 댓글 좋아요 동시성 문제를 핸들링 하였습니다.
- 게시글 좋아요, 댓글 좋아요 서비스에서 pk로 조회하는 쿼리에서 row lock을 걸어 동시성을 처리하였습니다.

[community] 커뮤니티 게시글, 댓글 좋아요 동시성 처리

---

build.gradle.kts
src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/team/root/application/dto/TeamApplyDto.kt
src/main/kotlin/gogo/gogostage/global/cache/CacheConstant.kt
src/main/kotlin/gogo/gogostage/global/config/RedisConfig.kt

팀 관련 조회 API에 캐시를 적용하였습니다.
- 임시 팀 리스트 조회, 출전 팀 리스트 조회, 팀 상세 조회 API에 캐시를 적용하였습니다.
- 캐시 저장소는 Redis 저장소를 사용하였습니다. (TTL 1시간)
- 만약 팀 추가시 임시 팀 리스트 캐시를 삭제하도록 이빅트를 설정해두었습니다.
- 기본 생성자 문제로 캐시 역직렬화 문제가 발생하였습니다. 우선 DTO 객체에 기본 값을 할당하여 해결해두었습니다. 추후 ObjectMapper 빈을 설정하여 해결할 예정입니다.

[team] 팀 조회 API 캐시 적용

---

src/main/kotlin/gogo/gogostage/domain/game/persistence/Game.kt
src/main/kotlin/gogo/gogostage/domain/match/result/persistence/MatchResult.kt
src/main/kotlin/gogo/gogostage/domain/match/result/persistence/MatchResultRepository.kt
src/main/kotlin/gogo/gogostage/domain/team/root/application/TeamProcessor.kt

팀 신청시 팀의 경기의 teamCount를 추가하는 로직을 작성하였습니다.
- Team 엔티티와 TeamResult 엔티티의 관계를 N:1 관계로 수정하였습니다.
- batch cancel 이벤트 핸들링시 match result 삭제 쿼리에 `@Modifying` 어노테이션을 추가하였습니다.

[team] 팀 신청시 경기 팀 수 추가

---

src/main/kotlin/gogo/gogostage/domain/community/comment/application/CommentReader.kt

댓글 좋아요 서비스에서 댓글 조회시 row lock을 잡는 메서드에서 lock을 잡는 repository method를 사용하지 않는 부분을 수정하였습니다.

[community] 댓글 좋아요 lock 메서드 사용하지 않는 부분 수정

---

src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchProcessor.kt
src/main/kotlin/gogo/gogostage/domain/team/root/persistence/Team.kt

정산 취소시 승리팀 win count를 rollback하도록 하였습니다.
- 정산 취소시 승리팀의 winCount 필드의 차감이 누락되어 추가하였습니다.

[batch] 정산 취소시 승리팀 win count rollback

---

src/main/kotlin/gogo/gogostage/domain/match/notification/application/MatchNotificationReader.kt
src/main/kotlin/gogo/gogostage/domain/match/notification/persistence/MatchNotification.kt
src/main/kotlin/gogo/gogostage/domain/match/notification/persistence/MatchNotificationRepository.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchProcessor.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchReader.kt

매치 알림을 토클하면 생기는 엔티티에서 연관관계가 잘못 설정 되어 있어 해결하였고 동시성 문제가 일어나 동시성 제어 하였습니다.
* tbl_match_notification 엔티티에서 matchId가 OneToOne으로 설정되어 UNIQUE 제약 조건이 걸려 생기던 오류를 ManyToOne으로 변경하여 해결하였습니다.
* 알림 토클을 하면서 동시성 문제가 발생하여 row lock을 걸어 제어하였습니다

[match] 매치 알림 토클 동시성 문제, 연관관계 문제 해결

---

src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/StageCustomRepositoryImpl.kt

랭킹 리스트 조회시 student id 필드의 매핑이 tbl_stage_participant.id로 매핑되는 이슈를 해결하였습니다.

[stage] 랭킹 리스트 조회시 student id 매핑 이슈 해결

---

src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt

GOGO for GSM 릴리즈에서는 사용되지 않는 기능인 사설 스테이지 생성 요청을 deny 처리하였습니다.

[deprecated] 사설 스테이지 생성 API

---

src/main/kotlin/gogo/gogostage/domain/game/application/GameMapper.kt
src/main/kotlin/gogo/gogostage/domain/game/application/GameService.kt
src/main/kotlin/gogo/gogostage/domain/game/application/GameServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/game/application/GameValidator.kt
src/main/kotlin/gogo/gogostage/domain/game/application/dto/GameDto.kt
src/main/kotlin/gogo/gogostage/domain/game/presentation/GameController.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchReader.kt
src/main/kotlin/gogo/gogostage/domain/match/root/persistence/MatchRepository.kt
src/main/kotlin/gogo/gogostage/global/config/SecurityConfig.kt

토너먼트 경기의 대진표 조회 API를 개발하였습니다.
- 토너먼트 경기의 매치들을 round 별로 나누어 각 팀 정보와 승리 팀 정보를 반환합니다.
- 해당 요청을 한 유저가 조회하려는 경기의 스테이지에 참여하고 있는지 검증합니다.
- 매치들 조회시 Game과 MatchResult엔티티 조회 JPQL 쿼리에 패치조인하여 쿼리 성능을 튜닝하였습니다.

[game] 경기 대진표 조회 API

---

src/main/kotlin/gogo/gogostage/domain/game/application/GameServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/game/application/dto/GameDto.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchProcessor.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/dto/MatchDto.kt
src/main/kotlin/gogo/gogostage/domain/stage/participant/root/application/ParticipateProcessor.kt
src/main/kotlin/gogo/gogostage/domain/stage/rule/application/StageRuleServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/team/root/application/dto/TeamApplyDto.kt
src/main/kotlin/gogo/gogostage/global/cache/CacheConstant.kt
src/main/kotlin/gogo/gogostage/global/cache/RedisCacheService.kt
src/main/kotlin/gogo/gogostage/global/config/RedisConfig.kt

스테이지 관련 API 캐시 적용 및 역직렬화 문제를 해결하였습니다.
- 스테이지에 등록된 경기 조회, 매치 상세 조회, 대진표 조회 API의 response를 캐시하였습니다.
- redis cache service를 두어 배팅 이벤트 핸들링시 해당 매치 상세 조회 key 삭제, 정산, 정산취소 이벤트 핸들링시 팀 리스트 조회, 대진표, 매치 상세 조회 key를 삭제 처리하였습니다.
- dto 객체 역직렬화 문제는 object mapper를 cache manger에 등록하고 activateDefaultTyping 설정과 필드 case 관련 설정을 추가하여 해결하였습니다.
- 하지만 `aTeam` 과 같은 필드는 직렬화시 `ateam` 과 같이 직렬화 되기 때문에 `@JsonProperty` 어노테이션으로 직접 매핑시켰습니다. 이로 인해 response에 중복되는 필드가 나타나는 이슈가 발생하였습니다. 추후 해결이 필요해보입니다.
```json
{
"matchId": 17,
"aTeam": {
...
},
"bTeam": {
...
},
...
// 중복 필드
"ateam": {
...
},
"bteam": {
...
}
}
```

[stage] 스테이지 관련 API 캐시 적용 및 역직렬화 문제 해결

---

src/main/kotlin/gogo/gogostage/domain/match/notification/application/MatchNotificationReader.kt
src/main/kotlin/gogo/gogostage/domain/match/root/application/MatchProcessor.kt

match 알림 토클 api에서 동시성 문제가 발생하여 로직으로 해결하였습니다.
서비스 로직에서 exist를 먼저 실행하는데 이때 동시에 접근하게 되면 row lock이 걸리지 않아 false로 뜰 경우 동시에 2개가 생성되는 문제가 생겨 조회할 때 nullable로 만들어 row lock을 걸고 그 뒤 if문으로 나뉘게 리팩토링하였습니다

[match] 매치 토글 알림 동시성 문제

---

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/global/cache/CacheConstant.kt
src/main/kotlin/gogo/gogostage/global/internal/user/stub/Sex.kt

커뮤니티 관련 API를 redis를 사용하여 캐싱하였습니다.
* boardInfo api에 레디스 캐시를 설정하였고 게시글 좋아요, 댓글 작성, 댓글 좋아요를 하게 되면 캐시를 지우게 설정하였습니다.
// 게시글 모두 불러오기 api는 페이징과 캐시를 remove해야되는 시점에서 key를 설정하기 적합하지 않아 캐싱하지 않았습니다.

[community] 커뮤니티 관련 API 캐싱

---

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt

댓글 좋아요를 누를 때 파라미터에 존재하지 않은 값으로 삭제를 시도해여 오류가 발생해 수정하였습니다.
service 메서드에서 진행하던 CacheEvict를 processor에서 redisCache를 직접 제거하는 방식으로 변경하였습니다.

[community] 올바르지 않은 key로 캐시 삭제

---

build.gradle.kts
src/main/kotlin/gogo/gogostage/global/feign/client/BettingClient.kt
src/main/kotlin/gogo/gogostage/global/feign/fallback/BettingClientFallbackFactory.kt

매치 검색시 사용하는 배팅 정보 일괄 조회 internal API client에서 오류 발생시 fallback 처리와 circuitbreaker를 적용하였습니다.
- 매치 검색시 Betting Service에 동기 HTTP 요청을 하게 되는데 요청하는 서비스에서 장애 발생시 매치 검색도 되지 않는 장애 전파 문제 있습니다.
- internal API 요청중 문제 발생시 fallback 메서드를 실행하도록 하였고, 아래의 설정에 의해 임계치 이상 실패시 circuitbreaker가 OPEN 되도록하여 장애 발생 서비스를 격리시킵니다.
```yaml
resilience4j:
circuitbreaker:
configs:
default:
failure-rate-threshold: 50
slow-call-rate-threshold: 80
slow-call-duration-threshold: 5s
permitted-number-of-calls-in-half-open-state: 3
max-wait-duration-in-half-open-state: 0
sliding-window-type: COUNT_BASED
sliding-window-size: 20
minimum-number-of-calls: 10
wait-duration-in-open-state: 15s
```

[internal] betting service client fallback, ciurcuitbreaker 적용

---

src/main/kotlin/gogo/gogostage/domain/community/board/application/BoardProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/board/persistence/Board.kt
src/main/kotlin/gogo/gogostage/domain/community/comment/persistence/Comment.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/listener/CommunityApplicationEventListener.kt
src/main/kotlin/gogo/gogostage/domain/community/root/event/BoardCreateEvent.kt
src/main/kotlin/gogo/gogostage/domain/community/root/event/CommentCreateEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/configuration/KafkaConsumerConfig.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/AiBoardFilterConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/AiCommentFilterConsumer.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/AiBoardFilterEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/consumer/dto/AiCommentFilterEvent.kt
src/main/kotlin/gogo/gogostage/global/kafka/properties/KafkaTopics.kt
src/main/kotlin/gogo/gogostage/global/kafka/publisher/StagePublisher.kt

게시글/댓글 욕설 필터를 위해 이벤트를 send하는 것과 검증되어 true라면 오는 이벤트를 컨슘하는 것을 만들었습니다.
* BoardCreateEvent / CommentCreateEvent 생성
* AiBoardFilterConsumer / AiCommenrFilterConsumer 추가

[community] 게시글 / 댓글 욕설 필터 이벤트 send와 이벤트 컨슈머 생성

---

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/global/cache/CacheConstant.kt

게시글 조회에 적용되어있는 캐시에 이슈가 발생하여 제거하였습니다.
- 게시글 상세 조회 api 스펙에 각 유저의 상태 값(isLiked)을 글로벌 캐시하여 여러 유저의 상태 값이 올바르지 않게 조회되었습니다.
- 이로인해 현재 구조에서는 우선 캐시 적용을 제거하여 문제를 해결하고 추후 더 나은 해결 방법을 고민해보는게 좋다고 판단하였습니다.

[community] 게시글 상세 조회 캐시 이슈로 인해 제거

---

src/main/kotlin/gogo/gogostage/domain/stage/root/persistence/StageCustomRepositoryImpl.kt

랭크 페이징을 하면서 orderBy의 조건문을 포인트의 내림차순으로 정렬하여 페이징할 떄마다 값이 달라지는 문제가 생겨 수정하였습니다.
* point만으로 내림차순으로 하게 되면 매번 요청마다의 순서가 보장되지 않아 orderBy에 studentId를 오름차순 정렬도 추가하였습니다.

[stage] rank 인원 순서 페이징 문제

---

src/main/kotlin/gogo/gogostage/domain/community/board/application/BoardProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/board/persistence/Board.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt

커뮤니티 게시글에 이미지를 업로드 할 수 있도록 컬럼을 추가하였습니다.
Image Upload API를 사용하여 반환된 url을 해당 필드에 넣어 요청을 보내면 Board 테이블에 존재하는 imageUrl에 추가 됩니다.

[community] 커뮤니티 게시글 이미지 업로드

---

src/main/kotlin/gogo/gogostage/domain/community/board/persistence/Board.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt

게시글 이미지 url 필드를 nullable하게 수정했습니다.

[community] 게시글 이미지 url 필드 nullable

---

src/main/kotlin/gogo/gogostage/domain/image/application/ImageValidator.kt

이미지 이름이 유효성 검사에서 올바른 이름이라도 통과되지 않아 수정하였습니다.
"." 으로 이름과 확장자를 검사하던 것을 마지막 "."으로 확장자를 가져오도록 하였고 만약 확장자가 없다면 빈 문자열을 넣어 if문에 걸리도록 하였습니다. 또한, 파일의 크기도 검사하는 로직을 추가하였습니다.

[image] 이미지 유효성 검사 로직 변경

---

src/main/kotlin/gogo/gogostage/GogoStageApplication.kt
src/main/kotlin/gogo/gogostage/domain/community/board/application/BoardProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/board/persistence/Board.kt
src/main/kotlin/gogo/gogostage/domain/community/boardview/persistence/BoardView.kt
src/main/kotlin/gogo/gogostage/domain/community/boardview/persistence/BoardViewRepository.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityServiceImpl.kt
src/main/kotlin/gogo/gogostage/domain/community/root/application/dto/CommunityDto.kt
src/main/kotlin/gogo/gogostage/domain/community/root/event/BoardViewEvent.kt
src/main/kotlin/gogo/gogostage/domain/community/root/event/handler/BoardViewEventHandler.kt
src/main/kotlin/gogo/gogostage/domain/community/root/persistence/CommunityCustomRepositoryImpl.kt
src/main/kotlin/gogo/gogostage/global/config/AsyncConfig.kt

게시글을 상세보기를 하게 되면 유저당 하나의 조회수가 오르게 개발하였습니다.
* 게시글 상세보기를 하게 되면 해당 유저가 BoardView에 존재하는지 확인 후 없다면 BoardView 객체를 생성하여 저장하고 해당 Board 객체에 1을 plus한 후 저장하게 됩니다.
* 그 후 readBoardInfo를 실행하여 내가 들어간 조회수까지 적용되어 반환되게 됩니다.

[community] 게시글 조회수 적용

---

src/main/kotlin/gogo/gogostage/domain/community/root/application/CommunityProcessor.kt

커뮤니티 게시글을 조회시 조회한 유저를 저장하는 중 이벤트 핸들러에서 조회한 학생의 id가 아닌 작성자의 id를 넣어 수정하였습니다.
BoardView 초기화시 authorId가 아닌 event 안에 studentId를 넣도록 수정하였습니다

[community] 조회수 저장시 studentId 초기화 문제
